json.name  @item.name
json.detail  @item.detail
json.condition  @item.condition
json.delivery_cost  @item.delivery_cost
json.delivery_prefecture  @item.delivery_prefecture
json.days_to_ship  @item.days_to_ship
json.delivery_method  @item.delivery_method
json.price  @item.price
json.category_id  @item.category_id
json.brand_id  @item.brand_id
